// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperJournal_Library.Models;

#nullable disable

namespace PaperJournal_Library.Migrations
{
    [DbContext(typeof(PaperJournalSp2023DBContext))]
    partial class PaperJournalSp2023DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PaperJournal_Library.Models.Account", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StaffID");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountFullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AccountPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AccountRole")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime");

                    b.HasKey("StaffId")
                        .HasName("PK__Account__96D4AAF714BF8003");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            StaffId = "ACC0055",
                            AccountEmail = "admin@SpringerLink.com",
                            AccountFullName = "Admin",
                            AccountPassword = "@abc",
                            AccountRole = 0,
                            Birthday = new DateTime(1990, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "ACC0006",
                            AccountEmail = "manager1@SpringerLink.com",
                            AccountFullName = "HR Manager 1",
                            AccountPassword = "@123",
                            AccountRole = 1,
                            Birthday = new DateTime(1991, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "ACC0009",
                            AccountEmail = "manager2@SpringerLink.com",
                            AccountFullName = "HR Manager 2",
                            AccountPassword = "@123",
                            AccountRole = 1,
                            Birthday = new DateTime(1992, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "ACC0007",
                            AccountEmail = "staff@SpringerLink.com",
                            AccountFullName = "Staff",
                            AccountPassword = "123@",
                            AccountRole = 2,
                            Birthday = new DateTime(1990, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PaperJournal_Library.Models.JournalInfo", b =>
                {
                    b.Property<int>("JournalId")
                        .HasColumnType("int")
                        .HasColumnName("JournalID");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JournalName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ShortJournalDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JournalId")
                        .HasName("PK__JournalI__2501038619640AE7");

                    b.ToTable("JournalInfo", (string)null);

                    b.HasData(
                        new
                        {
                            JournalId = 4440,
                            Category = "Computer Science, AI, Data Mining",
                            JournalName = "International Journal of Computational Vision and Robotics",
                            ShortJournalDescription = "IJCVR is an international refereed journal in the field of image processing, pattern recognition, machine vision and image understanding, providing an international forum for professionals, engineers and researchers.",
                            Telephone = "1880903914555"
                        },
                        new
                        {
                            JournalId = 4441,
                            Category = "Data Science, Data Mining, AI",
                            JournalName = "International Journal of Data Analysis Techniques and Strategies",
                            ShortJournalDescription = "IJDATS bridges three gaps: firstly, a gap between academic ivory tower and the real world; secondly, a gap between quantitative data analysis techniques and qualitative data analysis techniques;",
                            Telephone = "1880903914555"
                        },
                        new
                        {
                            JournalId = 4450,
                            Category = "Information System, AI, Machine Learning",
                            JournalName = "International Journal of Information and Coding Theory",
                            ShortJournalDescription = "IJICoT publishes state-of-the-art international research that significantly advances the study of information and coding theory and their applications to cryptography, ... ",
                            Telephone = "1880903914555"
                        },
                        new
                        {
                            JournalId = 4460,
                            Category = "AI, Optimization Problem",
                            JournalName = "International Journal of Artificial Intelligence and Soft Computing",
                            ShortJournalDescription = "IJAISC provides a new forum for dissemination of knowledge on both theoretical and applied research on artificial intelligence.",
                            Telephone = "1880903914555"
                        },
                        new
                        {
                            JournalId = 4476,
                            Category = "Database, IS, AI",
                            JournalName = "International Journal of Intelligent Information and Database Systems",
                            ShortJournalDescription = "IJIIDS focuses on research in applications of advanced intelligent technologies for data storing/processing in a wide-ranging context.",
                            Telephone = "1880903914555"
                        });
                });

            modelBuilder.Entity("PaperJournal_Library.Models.Paper", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PaperID");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authors")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int")
                        .HasColumnName("JournalID");

                    b.Property<string>("PaperTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PaperId");

                    b.HasIndex("JournalId");

                    b.ToTable("Paper", (string)null);

                    b.HasData(
                        new
                        {
                            PaperId = "PP0020",
                            Abstract = "The efficient and effective process of extracting the useful information from high-dimensional data is worth studying. High-dimensional data is big and complex and that it becomes difficult process and classify. Dimensionality reduction (DR) is important and the key method to address these problems. This paper presents a hybrid approach for data classification constituted from the combination of principal component analysis (PCA) and enhanced extreme learning machine (EELM).",
                            Authors = "Doaa L. El-Bably; Khaled M. Fouad",
                            JournalId = 4476,
                            PaperTitle = "A hybrid approach for improving data classification based on PCA and enhanced ELM",
                            SubmittedDate = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaperId = "PP0021",
                            Abstract = "For the past decade, the utilisation of sensor devices in real world applications has increased rapidly. To meet the demand of applications, the sensor nodes are deployed in remote areas where the operation is very complex. The security of the sensor nodes may be compromised at any time. Therefore, a secure data aggregation mechanism is needed to overcome their limitations.",
                            Authors = "A.L. Sreenivasulu; P. Chenna Reddy",
                            JournalId = 4476,
                            PaperTitle = "An enhanced secure data aggregation routing protocol for sensor networks",
                            SubmittedDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaperId = "PP0022",
                            Abstract = "Now-a-days student absenteeism in engineering education is a most important issue of a professional institution which affects the overall performance of institutions. This is most imperative alarm in creating outstanding engineers (real engineers) to the country. The quality of education is directly proportional to student absenteeism. ",
                            Authors = "I. Samuel Peter James; P. Ramasubramanian; D. Magdalene Delighta Angeline",
                            JournalId = 4476,
                            PaperTitle = "Student absenteeism in engineering college using rough set and data mining approach",
                            SubmittedDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaperId = "PP0023",
                            Abstract = "In this paper, a radial basis function neural network (RBFN) model has been trained by canonical particle swarm optimisation (PSO) and improved particle swarm optimisation (IMPSO) algorithms to efficiently predict the exchange rate of Indian rupees against the exchange rate of G-7 countries for future days.",
                            Authors = "Trilok Nath Pandey; Alok Kumar Jagadev; Satchidananda Dehuri; Sung-Bae Cho",
                            JournalId = 4476,
                            PaperTitle = "Prediction of exchange rate using improved particle swarm optimised radial basis function networks",
                            SubmittedDate = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaperId = "PP0024",
                            Abstract = "Most people face the dilemma of accepting photographs as authentic or not, mainly in the case of forensics, where the images will influence judgment. Research communities are constantly providing methods to identify these kinds of forged images.",
                            Authors = "Tarun Kumar; Gourav Khurana",
                            JournalId = 4441,
                            PaperTitle = "Copy-move image forgery detection using cuckoo search",
                            SubmittedDate = new DateTime(2022, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaperId = "PP0015",
                            Abstract = "Plant diseases are the main cause of economic losses in the agricultural field. In India, the most significant staple food consumed is rice. Different kinds of disease of rice namely grain discoloration, sheath blight, brown spot, and blast are the main restriction on rice harvesting or production and explosion being the most demoralising disease.",
                            Authors = "T. Gayathri Devi; P. Neelamegam; A. Srinivasan",
                            JournalId = 4441,
                            PaperTitle = "Rice plant disease, crop stages endemic and control measures - a survey",
                            SubmittedDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaperId = "PP0027",
                            Abstract = "Image processing is crucial in any image analysis to determine the problem. If it is a medical area, a suitable image processing method becomes even more imperative to get as accurate results as possible. Due to the widespread outbreak of coronavirus disease 2019 (COVID-19), an infectious respiratory disease, it has become quite urgent that a reliable method for identification of the disease is sought.",
                            Authors = "Fariha Noor; Md. Rashad Tanjim; Muhammad Jawadur Rahim; Md. Naimul Islam Suvon; Faria Karim Porna;",
                            JournalId = 4441,
                            PaperTitle = "Application of fuzzy logic on CT-scan images of COVID-19 patients",
                            SubmittedDate = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PaperJournal_Library.Models.Paper", b =>
                {
                    b.HasOne("PaperJournal_Library.Models.JournalInfo", "Journal")
                        .WithMany("Papers")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Paper__JournalID__286302EC");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("PaperJournal_Library.Models.JournalInfo", b =>
                {
                    b.Navigation("Papers");
                });
#pragma warning restore 612, 618
        }
    }
}
